import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import FormbricksProvider from '@/components/FormBricks';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
        <FormbricksProvider />
      </Suspense>
      <script async src="https://tally.so/widgets/embed.js"></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
