import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';
import FormbricksProvider from '@/components/FormBricks';
import { Suspense } from 'react';
import { Toaster } from '@/components/ui/toaster';

const workSans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
        <FormbricksProvider />
      </Suspense>
      <body className={workSans.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
